### ISSUE TITLE
Feature Request: Client Side Decorations (aka: GTK Native Titlebar)

### ISSUE THREAD

**Issue by ant-ms** [discordlinux/feedback#49]
Discord just looks completely out of place on a modern Linux (GNOME) desktop, I made this mock-up to show how I wish it looked.
![image](https://user-images.githubusercontent.com/23363161/116567166-ac914980-a907-11eb-8416-663fae280286.png)
(Not exactly like this, but you get the idea)

**Comment by junetried** [comment]
Oh, sorry but this repository is feedback *for* a Discord server about Linux. It doesn't have any attachment to the official clients.
