### ISSUE TITLE
Change how unsupported distributions appear in rules

### ISSUE THREAD

**Issue by junetried** [discordlinux/feedback#52]
```
• The following distributions are not supported in Discord Linux:
Kali Linux, Parrot OS, any pentesting distro, Linux Mint, Solus, Manjaro, any derivative of Arch Linux, or any unofficial derivative of Debian or Ubuntu (other than KDE neon).
```
This seems rather unsatisfactory to me. It has redundancies while also not covering some common cases. It's also a bit cramped. I think something like this would be better:

```
The following distributions are not supported in Discord Linux:
  • Kali Linux, Parrot OS, or any other pentesting distro
  • Solus
  • Any derivative of Arch Linux, including "install scripts"
  • Most unofficial derivatives of Debian or Ubuntu (including Linux Mint)
  • Any version or flavor of Ubuntu which is not an LTS version
```
Reasoning:

Breaking it up like this makes it easier to scan through and would make it visually distinct from the next bullet points, which do not list unsupported distros. It also makes it easier to add to in the future.

Specifying "**or** any pentesting distro" relates Kali and Parrot with 'pentesting distro' and makes it look less like a typo.

Sometimes the Arch install scripts come up, and they aren't supported. Especially with the official(er) install script, this feels appropriate to include.

Most Manjaro users are aware their distro is Arch-based, so it's probably not necessary to include. I considered doing the same for Parrot and Kali, but I don't think the same reasoning applies.

Changing "Any unofficial derivative of Debian or Ubuntu" to "Most" because it happens on a per-distro basis. Distros like Raspbian/Raspberry Pi OS and KDE Neon are supported, both of which fall under "Any unofficial derivative". Moved Mint here since it also applies and is a high-profile case.

Finally, the non-LTS thing comes up a lot, and confuses and frustrates people since it's currently missing from the rules entirely. I feel like if none of the other changes happen, this one still deserves to.

**Comment by simoniz0r** [comment]
This is now fully implemented.  Thanks for the suggestion 👍
