### ISSUE TITLE
#news -> Announcements

### ISSUE THREAD

**Issue by NamelessGO** [discordlinux/feedback#57]
Use case: users will be able to follow this news channels outside of the server, making it a rss channel for multiple discord servers

https://support.discord.com/hc/en-us/articles/360032008192-Announcement-Channels-

**Comment by wuulfy** [comment]
Chipping to say that I agree with this idea and is painless to setup, can see good function out of this ^

**Comment by simoniz0r** [comment]
Everything there is already *from* RSS feeds, and none of it is original content, so I don't see the point of this.
