### ISSUE TITLE
Why must a new .deb file be downloaded for every update

### ISSUE THREAD

**Issue by millersartin** [discordlinux/feedback#61]
Every update a new .deb file has to be downloaded via my browser and then installed. Why must it be this way? I do not understand why the update cannot just replace existing code in the application. Gets even more silly when you realize discord is just a web app.

**Comment by Alxhr0** [comment]
I think you got the wrong repo buddy?

**Comment by madmaxgrey** [comment]
hey miller you've gotten the wrong repo this github is for the discord linux server which is not affliated with discord, the feedback part is for members to give feedback on our server, but to help with your issue goto syretia github and download the discord stable appimage, when ever theres a new discord version it auto updates and you just have to click next and okay no new downloads

**Comment by millersartin** [comment]
Thank you, my bad
