### ISSUE TITLE
disable MANDATORY UPDATE on linux .

### ISSUE THREAD

**Issue by ArMot** [discordlinux/feedback#63]
Using mandatory update is an awful idea, specially when there is no breaking changes .
I use discord all the time to communicate with the team of developers and guess what. From time to time. Discord asks me to update to latest version. although there is no update in pacman repository (Arch linux) yet. 
so Every few days . I have to edit this file:

/opt/discord/resources/build_info.json 
and change version number to be able to use discord again . and for what ! I mean ... there is not that much of a breaking changes . So Why You force it ?

**Comment by junetried** [comment]
This repo is not for tracking client issues, and you're in the wrong place.

For your issue, I happen to have [a sort of Discord launcher project](https://github.com/junetried/python_discord_launcher) that might help you. There's also the [Discord updater AppImage](https://github.com/simoniz0r/Discord-AppImage) which is maintained by Syretia.
