### ISSUE TITLE
screen sharing DO NOT WORK in WAYLAND !

### ISSUE THREAD

**Issue by ArMot** [discordlinux/feedback#64]
This is somehow and old issue for me but it has not been fixed yet !!
It's been some time that Modern linux systems moved from X to Wayland protocols . but Still I'm not able to share my screen in wayland !

people have to use firefox/chrome web app version of discord so they can share screen, show teammate/friends something and then again get back to desktop version ! :)
That's kinda terrible experience for users ...

**Comment by junetried** [comment]
This repo is not for tracking client issues, and you're in the wrong place.
