### ISSUE TITLE
Tweaking the Welcome Process

### ISSUE THREAD

**Issue by simoniz0r** [discordlinux/feedback#8]
I've been working on tweaking the process for <#479497706234970115> a bit, and I've been trying to think of something easier than entering a passphrase for making sure that people who join are actually people and not bots.

An idea that I've been throwing around is having the person add 2 or 3 random reactions from our emoji list in Discord Linux to the message that mentions them in <#479497706234970115>.  These emojis would be listed in the link given to the person in their welcome message just as the current passphrase is.

My main concern with this is that it might actually be more confusing for the person to find the specific message that mentions them and add reactions to it than the current passphrase system is.

The current passphrase system also doesn't seem to be too difficult for the majority of people.  Quite a few people actually get in on their first try, and most people get in in 5 or less tries.

Thoughts on this idea?  Is the system fine as is?  Other ideas?

**Comment by adhdluke** [comment]
If it's not too much work, I think it would be interesting to test it out for a week or two, and ask new users what they think of it.
